version: '3.8'

services:
  db:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    networks:
      - qdrant-net
  ai:
    build:
      context: .
      dockerfile: Dockerfile
      target: ai
    ports:
      - "3333:3333"
    environment:
      VECTOR_DB_URL: "http://127.0.0.1:6333/"
      COLLECTION: "Akinator"
    networks:
      - qdrant-net
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "3000:3000"

networks:
  qdrant-net:
    external:
      name: qdrant-net
